local vsColors = require 'user/default_theme/vscode-colors'

local highlights = {
  ["@method"] = { fg = vsColors.vscYellow },
  ['@error'] = { fg = vsColors.vscRed },
  ['@punctuation.bracket'] = { fg = vsColors.vscFront },
  ['@punctuation.special'] = { fg = vsColors.vscFront },
  ['@comment'] = { fg = vsColors.vscGreen },
  ['@constant'] = { fg = vsColors.vscYellow },
  ['@constant.builtin'] = { fg = vsColors.vscBlue },
  ['@constant.macro'] = { fg = vsColors.vscBlueGreen },
  ['@string.regex'] = { fg = vsColors.vscOrange },
  ['@string'] = { fg = vsColors.vscOrange },
  ['@character'] = { fg = vsColors.vscOrange },
  ['@number'] = { fg = vsColors.vscLightGreen },
  ['@boolean'] = { fg = vsColors.vscBlue },
  ['@float'] = { fg = vsColors.vscLightGreen },
  ['@annotation'] = { fg = vsColors.vscYellow },
  ['@attribute'] = { fg = vsColors.vscBlueGreen },
  ['@namespace'] = { fg = vsColors.vscBlueGreen },
  ['@function.builtin'] = { fg = vsColors.vscYellow },
  ['@function'] = { fg = vsColors.vscYellow },
  ['@function.macro'] = { fg = vsColors.vscYellow },
  ['@parameter'] = { fg = vsColors.vscLightBlue },
  ['@parameter.reference'] = { fg = vsColors.vscLightBlue },
  ['@method'] = { fg = vsColors.vscYellow },
  ['@field'] = { fg = vsColors.vscLightBlue },
  ['@property'] = { fg = vsColors.vscLightBlue },
  ['@constructor'] = { fg = vsColors.vscBlueGreen },
  ['@conditional'] = { fg = vsColors.vscPink },
  ['@repeat'] = { fg = vsColors.vscPink },
  ['@label'] = { fg = vsColors.vscLightBlue },
  ['@keyword'] = { fg = vsColors.vscPink },
  ['@keyword.function'] = { fg = vsColors.vscBlue },
  ['@keyword.operator'] = { fg = vsColors.vscBlue },
  ['@operator'] = { fg = vsColors.vscFront },
  ['@exception'] = { fg = vsColors.vscPink },
  ['@type'] = { fg = vsColors.vscBlueGreen },
  ['@type.builtin'] = { fg = vsColors.vscBlue },
  ['@structure'] = { fg = vsColors.vscLightBlue },
  ['@include'] = { fg = vsColors.vscPink },
  ['@variable'] = { fg = vsColors.vscLightBlue },
  ['@variable.builtin'] = { fg = vsColors.vscLightBlue },
  ['@text'] = { fg = vsColors.vscFront },
  ['@text.underline'] = { fg = vsColors.vscYellowOrange },
  ['@tag'] = { fg = vsColors.vscBlue },
  ['@tag.delimiter'] = { fg = vsColors.vscGray },
  ['@tag.attribute'] = { fg = vsColors.vscLightBlue },

  ['@text.title'] = { fg = vsColors.vscBlue },
  ['@text.literal'] = { fg = vsColors.vscFront },
  ['markdown@text.literal'] = { fg = vsColors.vscOrange },
  ['markdown_inline@text.literal'] = { fg = vsColors.vscOrange },
  ['@text.emphasis'] = { fg = vsColors.vscFront },
  ['@text.strong'] = { fg = vsColors.vscBlue },
  ['@text.uri'] = { fg = vsColors.vscFront },
  ['@textReference'] = { fg = vsColors.vscOrange },
  ['@punctuation.delimiter'] = { fg = vsColors.vscFront },
  ['@stringEscape'] = { fg = vsColors.vscOrange },

  ['@text.note'] = { fg = vsColors.vscBlueGreen },
  ['@text.warning'] = { fg = vsColors.vscYellowOrange },
  ['@text.danger'] = { fg = vsColors.vscRed },
}

return highlights
